### ISSUE TITLE
Carriage Returns

### ISSUE THREAD

**Issue by mikerockett** [xv1t/OpenDocumentTemplate#1]
Hi - great project, thanks for sharing.

I'm unable to create carriage returns for my ODT file using `\n`. Is there another way I can do this?

For some insight, this is for a physical/postal address field that needs to appear on an invoice. I do not want to split the field over four lines in the template as some addresses only have three lines.

Please advise, thank you.

PS: The composer install-method does not work in Laravel. I need to specify `@dev` when installing, but then the class is not found. You need to add the applicable autoloader to your composer file in order for it to work.

**Comment by xv1t** [comment]
Hi Mike!

Thanks for kind words.

Interesting question, never thought to come in handy, but I'll try to help.

Your input array data looks like this?
```php
$data = array(
  'emails' => "email1@example.com\nemail2@example.com\nemail3@example.com"
);
```
Try this recomendation:
Your emails convert to array
```php
$emails = array(
  'email1@example.com',
  'email2@example.com',
  'email3@example.com',
);
```
And implode to the this string:
```php
$data = array(
   'emails' => implode("\n<text:line-break/>\n", $emails)
);
```
And render your ODT again. If was errors please notice me.

PS: about composer, a dont used composer, but if your send me a patched composer file, I would be grateful to you!

**Comment by mikerockett** [comment]
Thanks - I'll give that a try soon.

Regarding Composer, I recommend that you namespace the the file and add it to the PSR4 autoloader. So at the top of the library, add:

```php
namespace Xv1t;
```

Then in your composer file, add:

```json
    "autoload": {
        "psr-4": {
            "Xv1t\\": "src/"
        }
    }
```

Given the above, you should also move the library to a new `src` directory.

Then, new instances of the class are created like this:

```php
$template = new Xv1t\OpenDocumentTemplate();
```

It can still be loaded either by composer or manually via `require_once` (recommended method).
